name: Update ECS Service with Load Balancer and Task Count

on:
  push:
    branches:
      - main  # Change this to your preferred branch

jobs:
  update-ecs-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Here, you might have a step to build your Docker image if needed

      - name: Deploy Amazon ECS frontend task definition
        id: deploy-ecs-task-def
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ github.sha }}
          service: arn:aws:ecs:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:service/food-order-app/myfoodapp
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          force-new-deployment: true

      - name: Update ECS service with load balancer and task count
        id: update-ecs-service
        run: |
          aws ecs update-service --cluster <CLUSTER_NAME> --service <SERVICE_NAME> --task-definition ${{ github.sha }} --desired-count 2
          aws ecs create-service-registry --registry-name <REGISTRY_NAME> --container-name <CONTAINER_NAME> --container-port <CONTAINER_PORT>
          aws ecs create-service --cluster <CLUSTER_NAME> --service-name <SERVICE_NAME> --launch-type FARGATE --desired-count 2 --task-definition ${{ github.sha }} --load-balancers targetGroupArn=<TARGET_GROUP_ARN>,containerName=<CONTAINER_NAME>,containerPort=<CONTAINER_PORT>